workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
